### ISSUE TITLE
Problème get_fid_state sur HA

### ISSUE THREAD

**Issue by francispoisson** [dvd-dev/python-hilo#3]
Lorsque j'essaie de me connecter à partir de HA:

Logger: homeassistant.setup
Source: custom_components/hilo2/__init__.py:39
Integration: Hilo HA integration (documentation, issues)
First occurred: 21:40:35 (1 occurrences)
Last logged: 21:40:35

Error during setup of component hilo2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/hilo2/__init__.py", line 39, in async_setup
    api = await API.async_auth(username, password, session=ClientSession())
  File "/usr/local/lib/python3.9/site-packages/pyhilo/api.py", line 135, in async_auth
    await api._get_fid()
  File "/usr/local/lib/python3.9/site-packages/pyhilo/api.py", line 224, in _get_fid
    if not self._get_fid_state():
  File "/usr/local/lib/python3.9/site-packages/pyhilo/api.py", line 192, in _get_fid_state
    fb_state = state.get("firebase", {})
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by francispoisson** [comment]
J'arrive à recréer le problème localement en supprimant le contenu du fichier hilo_state.yaml.

**Comment by francispoisson** [comment]
J'ai l'impression que le module n'arrive pas à trouver le fichier hilo_state.yaml sur HA.

**Comment by valleedelisle** [comment]
J'imagine que c'est regled.
